-- Aurora template (travel) — catalog + store_content_blocks (deterministic UUIDs)
-- Apply after tenant schema + tables exist (pnpm schema:provision or Studio).
--
-- 1) Replace __TENANT_UUID__ with your Aurora tenant id (UUID with dashes).
-- 2) Replace __TENANT_SCHEMA__ with tenant_<uuid with underscores not dashes>
--    Example: uuid 550e8400-e29b-41d4-a716-446655440000 -> schema tenant_550e8400_e29b_41d4_a716_446655440000
--
-- 3) Run: psql $DATABASE_URL -v ON_ERROR_STOP=1 -f init/seed.sql
--    or paste into Studio SQL editor (adjust search_path if needed).
--
-- Re-run safe: deletes seed SKUs/slugs for this vertical before insert.
-- After apply: reindex Meilisearch for the tenant.

BEGIN;

-- Clean previous seed rows for this vertical (idempotent)
DELETE FROM __TENANT_SCHEMA__.store_content_blocks WHERE tenant_id = '__TENANT_UUID__'::uuid AND slug LIKE 'seed-cb-travel-%';
DELETE FROM __TENANT_SCHEMA__.products WHERE tenant_id = '__TENANT_UUID__'::uuid AND sku LIKE 'SEED-TEMPLATE-TRAVEL-%';
DELETE FROM __TENANT_SCHEMA__.categories WHERE tenant_id = '__TENANT_UUID__'::uuid AND slug IN ('template-travel-luggage', 'template-travel-guides', 'template-travel-accessories');
DELETE FROM __TENANT_SCHEMA__.zones WHERE tenant_id = '__TENANT_UUID__'::uuid AND slug = 'template-travel-seed-zone';
DELETE FROM __TENANT_SCHEMA__.vendors WHERE tenant_id = '__TENANT_UUID__'::uuid AND id = 'deda0770-1d85-42e9-9bca-03cbd9ae058d'::uuid;

INSERT INTO __TENANT_SCHEMA__.vendors (id, tenant_id, name, email, status, created_at, updated_at)
VALUES ('deda0770-1d85-42e9-9bca-03cbd9ae058d'::uuid, '__TENANT_UUID__'::uuid, 'Seed — Example Travel supply', 'seed-travel@example.com', 'active', now(), now());

INSERT INTO __TENANT_SCHEMA__.zones (id, tenant_id, slug, name, sort_order, vendor_id, created_at, updated_at)
VALUES ('df3dc8af-ac30-49f3-83b4-a51cf3bcd52a'::uuid, '__TENANT_UUID__'::uuid, 'template-travel-seed-zone', 'Travel shop', 1, 'deda0770-1d85-42e9-9bca-03cbd9ae058d'::uuid, now(), now());

INSERT INTO __TENANT_SCHEMA__.categories (id, tenant_id, name, slug, zone_id, created_at, updated_at)
VALUES ('9d9f17c7-8632-4bb2-96f8-431bfdd16b1b'::uuid, '__TENANT_UUID__'::uuid, 'Luggage', 'template-travel-luggage', 'df3dc8af-ac30-49f3-83b4-a51cf3bcd52a'::uuid, now(), now());
INSERT INTO __TENANT_SCHEMA__.categories (id, tenant_id, name, slug, zone_id, created_at, updated_at)
VALUES ('de694a67-6587-41f9-9f98-bb4f8c2b052c'::uuid, '__TENANT_UUID__'::uuid, 'Guides & maps', 'template-travel-guides', 'df3dc8af-ac30-49f3-83b4-a51cf3bcd52a'::uuid, now(), now());
INSERT INTO __TENANT_SCHEMA__.categories (id, tenant_id, name, slug, zone_id, created_at, updated_at)
VALUES ('55e920f5-57df-431b-b162-9e4672305248'::uuid, '__TENANT_UUID__'::uuid, 'Travel accessories', 'template-travel-accessories', 'df3dc8af-ac30-49f3-83b4-a51cf3bcd52a'::uuid, now(), now());

INSERT INTO __TENANT_SCHEMA__.products (id, tenant_id, name, description, price, sku, stock_quantity, image_url, category_id, vendor_id, tags, created_at, updated_at)
VALUES ('b93e6e64-bd44-47db-bcf7-f12933160ffd'::uuid, '__TENANT_UUID__'::uuid, 'Hardshell cabin case 55cm', 'Four-wheel spinner, TSA lock — fits most airline overhead bins.', 119, 'SEED-TEMPLATE-TRAVEL-01', 50, 'https://images.pexels.com/photos/2646521/pexels-photo-2646521.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '9d9f17c7-8632-4bb2-96f8-431bfdd16b1b'::uuid, 'deda0770-1d85-42e9-9bca-03cbd9ae058d'::uuid, 'hero, new_arrival', now(), now());
INSERT INTO __TENANT_SCHEMA__.products (id, tenant_id, name, description, price, sku, stock_quantity, image_url, category_id, vendor_id, tags, created_at, updated_at)
VALUES ('85c9817c-0e70-40fa-99eb-756be917a2b7'::uuid, '__TENANT_UUID__'::uuid, 'Packing cubes set (6)', 'Compress clothes and separate clean from laundry.', 32, 'SEED-TEMPLATE-TRAVEL-02', 50, 'https://images.pexels.com/photos/4004226/pexels-photo-4004226.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '9d9f17c7-8632-4bb2-96f8-431bfdd16b1b'::uuid, 'deda0770-1d85-42e9-9bca-03cbd9ae058d'::uuid, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.products (id, tenant_id, name, description, price, sku, stock_quantity, image_url, category_id, vendor_id, tags, created_at, updated_at)
VALUES ('f5efb59a-fb69-45ab-83b5-2fb5a386dfb5'::uuid, '__TENANT_UUID__'::uuid, 'Weekend city guide (demo)', 'Curated walks, transit tips, and neighbourhood eats.', 14, 'SEED-TEMPLATE-TRAVEL-03', 50, 'https://images.pexels.com/photos/122162/pexels-photo-122162.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'de694a67-6587-41f9-9f98-bb4f8c2b052c'::uuid, 'deda0770-1d85-42e9-9bca-03cbd9ae058d'::uuid, 'seasonal', now(), now());
INSERT INTO __TENANT_SCHEMA__.products (id, tenant_id, name, description, price, sku, stock_quantity, image_url, category_id, vendor_id, tags, created_at, updated_at)
VALUES ('bb70d289-b9f5-441e-bde7-dc78b344af8e'::uuid, '__TENANT_UUID__'::uuid, 'Waterproof trail map pack', 'Foldable maps for day hikes — tear-resistant.', 12, 'SEED-TEMPLATE-TRAVEL-04', 50, 'https://images.pexels.com/photos/7009483/pexels-photo-7009483.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'de694a67-6587-41f9-9f98-bb4f8c2b052c'::uuid, 'deda0770-1d85-42e9-9bca-03cbd9ae058d'::uuid, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.products (id, tenant_id, name, description, price, sku, stock_quantity, image_url, category_id, vendor_id, tags, created_at, updated_at)
VALUES ('6ed17cad-0d7e-4fb1-b1f9-06197117318d'::uuid, '__TENANT_UUID__'::uuid, 'Memory-foam travel pillow', 'Ergonomic neck support with washable cover.', 26, 'SEED-TEMPLATE-TRAVEL-05', 50, 'https://images.pexels.com/photos/5158947/pexels-photo-5158947.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '55e920f5-57df-431b-b162-9e4672305248'::uuid, 'deda0770-1d85-42e9-9bca-03cbd9ae058d'::uuid, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.products (id, tenant_id, name, description, price, sku, stock_quantity, image_url, category_id, vendor_id, tags, created_at, updated_at)
VALUES ('d6cfe58a-9381-4660-a22e-8d5d869fed1b'::uuid, '__TENANT_UUID__'::uuid, 'Universal USB-C travel adapter', 'UK/EU/US plugs with 65W USB-C PD.', 38, 'SEED-TEMPLATE-TRAVEL-06', 50, 'https://images.pexels.com/photos/3921632/pexels-photo-3921632.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '55e920f5-57df-431b-b162-9e4672305248'::uuid, 'deda0770-1d85-42e9-9bca-03cbd9ae058d'::uuid, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('2f1bf373-de01-497c-808e-5d5e7015e942'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-home-main-products', 0, 'home', 'home_main_feed', 'full', 'product_list', 'Trip-ready retail picks', 'Cabin bags, guides, adapters, and comfort items — matched to search and cart context.', NULL, NULL, NULL, NULL, 'b93e6e64-bd44-47db-bcf7-f12933160ffd,85c9817c-0e70-40fa-99eb-756be917a2b7,f5efb59a-fb69-45ab-83b5-2fb5a386dfb5,bb70d289-b9f5-441e-bde7-dc78b344af8e,6ed17cad-0d7e-4fb1-b1f9-06197117318d,d6cfe58a-9381-4660-a22e-8d5d869fed1b', NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('4dfbcc4e-2e5f-4715-9bbf-b49ca420b35c'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-home-main-search', 1, 'home', 'home_main_feed', 'full', 'search_terms', 'Travellers also pack', 'OR search across luggage, guides, and accessories in one pass.', NULL, NULL, NULL, NULL, NULL, 'cabin case, adapter, neck pillow, packing cubes, guidebook, map', NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('531b2a9e-fb2a-40ea-bcfe-096ccd80b2a5'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-home-main-blurb', 2, 'home', 'home_main_feed', 'full', 'blurb', 'Build the journey, then the basket', NULL, 'Holmes ties missions to departure dates and destinations; CMS sells add-ons (seat comfort, guides, insurance hints) without redeploys.', NULL, '/catalogue', 'Browse travel shop', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('12c2dcee-b572-4161-ba50-ec60c40dd4ac'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-home-main-half-a', 3, 'home', 'home_main_feed', 'half', 'blurb', 'Carry-on essentials', NULL, 'Cubes, cases, and TSA-friendly kits — ideal for city breaks and short hops.', NULL, '/catalogue?category=template-travel-luggage', 'Luggage', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('28e0e8f9-5427-435b-8c8e-54e5efd63199'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-home-main-half-b', 4, 'home', 'home_main_feed', 'half', 'blurb', 'On-the-ground planning', NULL, 'Guides and waterproof maps for walking trips — pair with accessories for long-haul comfort.', NULL, '/catalogue?category=template-travel-guides', 'Guides & maps', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('deeb3ea3-f765-45c7-a382-30b0d32cb115'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-home-main-image', 5, 'home', 'home_main_feed', 'full', 'image_blurb', 'Package-style weekend savings', NULL, 'Use as a hero ribbon for flight+hotel-style bundles translated into retail SKUs.', 'https://images.pexels.com/photos/6356303/pexels-photo-6356303.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '/offers', 'See offers', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('3d06c507-ed77-46a0-b6da-46742a277400'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-home-below-well', 1, 'home', 'home_below_context_well', 'full', 'blurb', 'Cut-offs & travel notices', NULL, 'Ferry strikes, baggage embargoes, or resort fees — short operational line above the feed.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('6de274b2-ffbc-41c9-818a-16aea91dd9e9'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-home-between-missions', 1, 'home', 'home_between_missions_and_feed', 'full', 'blurb', 'Rewards & partners', NULL, 'Miles, lounge passes, or car-hire partners — two sentences max.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('f9203a3c-4757-43af-962c-76d405d2f748'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-home-below-feed', 1, 'home', 'home_below_feed', 'full', 'blurb', 'Meal ideas between legs', NULL, 'Recipe missions for self-catering and airport-friendly meals.', NULL, '/recipes', 'Recipe ideas', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('a683833c-1b55-4b6f-aba1-3a52971f532a'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-for-you-blocks', 1, 'for_you', 'for_you_below_cart_blocks', 'full', 'search_terms', 'Last-minute departures', 'Adapters, comfort, and reading before you pay.', NULL, NULL, NULL, NULL, NULL, 'adapter, pillow, guide, map, usb, luggage', NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('e43f755e-805f-48ef-bd37-eb692313239c'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-for-you-header', 1, 'for_you', 'for_you_below_header', 'full', 'blurb', 'From your itinerary', NULL, 'Holmes bundles; CMS adds static tips (“Add EU plug if landing in Paris”).', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('9aa79823-7cbd-4085-81e4-4fd68164f661'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-cat-above', 1, 'catalogue', 'catalogue_above_grid', 'full', 'blurb', 'One grid for the whole trip', NULL, 'Filter luggage, guides, accessories. Search accepts natural phrases (“carry on weekend”).', NULL, '/catalogue', 'Reset filters', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('2df4d715-b4f8-4ff5-8d56-0ea11269b936'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-cat-below', 1, 'catalogue', 'catalogue_below_filters', 'full', 'search_terms', 'Trending searches', 'Broad OR across travel retail.', NULL, NULL, NULL, NULL, NULL, 'cabin, adapter, pillow, cubes, guide, map', NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('43990968-5636-463e-8727-dd1e68a32097'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-cat-luggage', 2, 'catalogue', 'catalogue_below_filters', 'full', 'blurb', 'Luggage aisle', NULL, 'You’re in Luggage — upsell cubes and locks. Link to accessories for long-haul.', NULL, '/catalogue?category=template-travel-accessories', 'Accessories', NULL, NULL, NULL, NULL, NULL, 'template-travel-luggage', now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('c2480d7b-cf3d-42b2-8a43-02bc9395b8aa'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-pdp-tabs', 1, 'product_detail', 'pdp_below_tabs', 'full', 'blurb', 'Fit & compliance', NULL, 'Airline size hints, battery rules for adapters, and ISBN for guides — keep compliance here.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('84daf7f6-c4f4-4ba7-bfd8-3a8d98755887'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-pdp-context', 1, 'product_detail', 'pdp_below_context', 'full', 'blurb', 'Returns & support', NULL, 'Link to your travel retail policy for opened guides or used comfort items.', NULL, '/about', 'Our standards', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('6739517a-43bc-4d66-9589-7b9aeb1a41f2'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-recipe-title', 1, 'recipe', 'recipe_below_title', 'full', 'blurb', 'Self-catering shortcuts', NULL, 'Meal missions that suit apartments and hostels — cross-sell small appliances if you stock them.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('27604899-f87b-4386-b8b4-9d48c559178c'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-recipe-ingredients', 1, 'recipe', 'recipe_below_ingredients', 'full', 'blurb', 'Missing an ingredient?', NULL, 'Search or For You — Holmes bundles grocery add-ons with the cart.', NULL, '/for-you', 'Open For You', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('e7b7d3fa-faa4-441e-b68a-cf0ad6f388de'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-recipe-index', 1, 'recipe_index', 'recipes_index_below_header', 'full', 'blurb', 'Eat well on the road', NULL, 'Keep recipe cards mobile-first for airport and train contexts.', NULL, '/', 'Back to home', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('ae511855-7ac0-4087-8967-2f6a8848b3dd'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-checkout-summary', 1, 'checkout', 'checkout_above_summary', 'full', 'blurb', 'Almost away', NULL, 'Digital vouchers vs shipped goods — align copy with fulfilment. Holmes still handles extras.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('e589c8d0-d0e8-43ec-bf80-c0888985ec53'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-checkout-sidebar', 1, 'checkout', 'checkout_sidebar', 'full', 'blurb', 'Need an agent?', NULL, 'Support hours and rebooking pointers — sidebar CMS.', NULL, '/about', 'Contact', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('9b38cc17-c5af-4706-ab8f-f26ce80f3d2c'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-cart-above', 1, 'cart', 'cart_above_lines', 'full', 'blurb', 'Review before you fly', NULL, 'Drop duplicate adapters or heavy guides if baggage is tight.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('84d6a6d0-015b-45f9-9581-835a2de72d53'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-cart-below-bundle', 1, 'cart', 'cart_below_bundle', 'full', 'blurb', 'Complete the trip', NULL, 'Cross-sell insurance hints, lounge passes, or guide add-ons.', NULL, '/catalogue?category=template-travel-accessories', 'Accessories', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('25badd60-f1ab-4c99-8356-af67e9382f3a'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-offers', 1, 'offers', 'offers_below_header', 'full', 'blurb', 'Live travel offers', NULL, 'Short intro — grid below does the selling. Think bundles and seasonal peaks.', NULL, '/catalogue', 'Shop all', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('42a5e231-bdad-4177-8fd7-b601442880f8'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-promotions', 1, 'promotions', 'promotions_below_header', 'full', 'blurb', 'Peak dates & school holidays', NULL, 'Align with email and partner campaigns — half-term, summer sun, ski season.', NULL, '/offers', 'See offers', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('e765d0c3-2585-4543-8501-2940465deaa3'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-about', 1, 'about', 'about_main', 'full', 'image_blurb', 'Example Travel shop', NULL, 'Aurora + Holmes + CMS blocks merchandise travel retail without shipping new storefront builds.', 'https://images.pexels.com/photos/3728284/pexels-photo-3728284.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '/catalogue', 'Browse shop', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
COMMIT;
