BEGIN;

DELETE FROM __TENANT_SCHEMA__.store_content_blocks WHERE tenant_id = '__TENANT_UUID__'::uuid AND slug LIKE 'seed-cb-travel-%';
DELETE FROM __TENANT_SCHEMA__.store_content_blocks WHERE tenant_id = '__TENANT_UUID__'::uuid AND (page, region, title) IN (('home', 'home_main_feed', 'Hand-picked legs of the trip'), ('home', 'home_main_feed', 'Book experiences like you pack a bag'), ('home', 'home_main_feed', 'From touchdown to last table'), ('home', 'home_main_feed', 'Guided tours & tickets'), ('home', 'home_main_feed', 'Transfers & trip services'), ('home', 'home_main_feed', 'Long-weekend bundles'), ('home', 'home_below_context_well', 'Cut-offs & travel notices'), ('home', 'home_between_missions_and_feed', 'Rewards & partners'), ('home', 'home_below_feed', 'Meal ideas between legs'), ('for_you', 'for_you_below_cart_blocks', 'Before you head to the gate'), ('for_you', 'for_you_below_header', 'Itinerary-aware add-ons'), ('catalogue', 'catalogue_above_grid', 'Plan flights, days, and add-ons together'), ('catalogue', 'catalogue_below_filters', 'Trending searches'), ('catalogue', 'catalogue_below_filters', 'Browsing experiences'), ('product_detail', 'pdp_below_tabs', 'Timing, fit & rules'), ('product_detail', 'pdp_below_context', 'Changes & refunds'), ('recipe', 'recipe_below_title', 'Self-catering shortcuts'), ('recipe', 'recipe_below_ingredients', 'Missing an ingredient?'), ('recipe_index', 'recipes_index_below_header', 'Eat well on the road'), ('checkout', 'checkout_above_summary', 'Tickets & fulfilment'), ('checkout', 'checkout_sidebar', 'Concierge & changes'), ('cart', 'cart_above_lines', 'Dates & overlap'), ('cart', 'cart_below_bundle', 'Add the missing leg'), ('offers', 'offers_below_header', 'Trip bundles'), ('promotions', 'promotions_below_header', 'Seasonal departures'), ('about', 'about_main', 'Experiences first, retail that keeps up'));

INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('2f1bf373-de01-497c-808e-5d5e7015e942'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-home-main-products', 0, 'home', 'home_main_feed', 'full', 'product_list', 'Hand-picked legs of the trip', 'Tours, transfers, maps, and carry-on comfort — surfaced together so guests plan and pay in one flow.', NULL, NULL, NULL, NULL, 'b93e6e64-bd44-47db-bcf7-f12933160ffd,85c9817c-0e70-40fa-99eb-756be917a2b7,f5efb59a-fb69-45ab-83b5-2fb5a386dfb5,bb70d289-b9f5-441e-bde7-dc78b344af8e,6ed17cad-0d7e-4fb1-b1f9-06197117318d,d6cfe58a-9381-4660-a22e-8d5d869fed1b,6e31d06d-b8b5-4b1d-a37b-d64a78982862,f54791f5-94e7-4435-a605-a4965250f785,eddb44e4-436c-4662-939e-1f4459f2f362,34e0966a-8ef1-4aec-8374-7d60405a6bda,aa86148e-3595-40cd-ad59-3961d9bf5925,f6194165-aecf-4009-99b5-cb932c3f6dfd', NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('4dfbcc4e-2e5f-4715-9bbf-b49ca420b35c'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-home-main-search', 1, 'home', 'home_main_feed', 'full', 'search_terms', 'Book experiences like you pack a bag', 'OR search mixes tours, airport rides, maps, and cabin comfort — one grid for the whole itinerary.', NULL, NULL, NULL, NULL, NULL, 'food tour, airport transfer, audio guide, packing cubes, esim, sunset cruise', NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('531b2a9e-fb2a-40ea-bcfe-096ccd80b2a5'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-home-main-blurb', 2, 'home', 'home_main_feed', 'full', 'blurb', 'From touchdown to last table', NULL, 'Lead with guided moments and reliable transfers, then upsell maps, adapters, and sleep kit. CMS blocks carry timing, meeting points, and baggage rules without a redeploy.', NULL, '/catalogue', 'Explore catalogue', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('12c2dcee-b572-4161-ba50-ec60c40dd4ac'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-home-main-half-a', 3, 'home', 'home_main_feed', 'half', 'blurb', 'Guided tours & tickets', NULL, 'Small-group walks, museums, and boat slots with duration in the title — perfect thumb-stopping half-width tiles on mobile.', NULL, '/catalogue?category=template-travel-tours', 'Tours & experiences', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('28e0e8f9-5427-435b-8c8e-54e5efd63199'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-home-main-half-b', 4, 'home', 'home_main_feed', 'half', 'blurb', 'Transfers & trip services', NULL, 'Private cars, shuttles, hire vouchers, and luggage forwarding — bookend flights so the retail story feels complete.', NULL, '/catalogue?category=template-travel-transfers', 'Transfers', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('deeb3ea3-f765-45c7-a382-30b0d32cb115'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-home-main-image', 5, 'home', 'home_main_feed', 'full', 'image_blurb', 'Long-weekend bundles', NULL, 'Ribbon for tour + transfer + guide packs — swap seasonally (city breaks, ski shuttles, summer boats).', 'https://images.pexels.com/photos/31109688/pexels-photo-31109688.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '/offers', 'See offers', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('3d06c507-ed77-46a0-b6da-46742a277400'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-home-below-well', 1, 'home', 'home_below_context_well', 'full', 'blurb', 'Cut-offs & travel notices', NULL, 'Ferry strikes, baggage embargoes, or resort fees — short operational line above the feed.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('6de274b2-ffbc-41c9-818a-16aea91dd9e9'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-home-between-missions', 1, 'home', 'home_between_missions_and_feed', 'full', 'blurb', 'Rewards & partners', NULL, 'Miles, lounge passes, or car-hire partners — two sentences max.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('f9203a3c-4757-43af-962c-76d405d2f748'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-home-below-feed', 1, 'home', 'home_below_feed', 'full', 'blurb', 'Meal ideas between legs', NULL, 'Recipe missions for self-catering and airport-friendly meals.', NULL, '/recipes', 'Recipe ideas', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('a683833c-1b55-4b6f-aba1-3a52971f532a'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-for-you-blocks', 1, 'for_you', 'for_you_below_cart_blocks', 'full', 'search_terms', 'Before you head to the gate', 'OR search for rides, data, and comfort layers that pair with tours already in the cart.', NULL, NULL, NULL, NULL, NULL, 'transfer, esim, neck pillow, phrasebook, padlock, rain jacket', NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('e43f755e-805f-48ef-bd37-eb692313239c'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-for-you-header', 1, 'for_you', 'for_you_below_header', 'full', 'blurb', 'Itinerary-aware add-ons', NULL, 'Holmes bundles legs of a trip; CMS adds meeting-point and baggage reminders (“Book shuttle 4h before flight”).', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('9aa79823-7cbd-4085-81e4-4fd68164f661'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-cat-above', 1, 'catalogue', 'catalogue_above_grid', 'full', 'blurb', 'Plan flights, days, and add-ons together', NULL, 'Filter tours, transfers, maps, and cabin gear. Natural search works (“sunset boat”, “airport car”, “packing cubes”).', NULL, '/catalogue', 'Reset filters', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('2df4d715-b4f8-4ff5-8d56-0ea11269b936'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-cat-below', 1, 'catalogue', 'catalogue_below_filters', 'full', 'search_terms', 'Trending searches', 'Broad OR across tours, rides, and trip retail.', NULL, NULL, NULL, NULL, NULL, 'food tour, shuttle, cabin case, map, adapter, bike pass', NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('43990968-5636-463e-8727-dd1e68a32097'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-cat-luggage', 2, 'catalogue', 'catalogue_below_filters', 'full', 'blurb', 'Browsing experiences', NULL, 'Pair tickets with transfers and pocket maps — fewer drop-offs when the next step is obvious.', NULL, '/catalogue?category=template-travel-transfers', 'Transfers & services', NULL, NULL, NULL, NULL, NULL, 'template-travel-tours', now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('c2480d7b-cf3d-42b2-8a43-02bc9395b8aa'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-pdp-tabs', 1, 'product_detail', 'pdp_below_tabs', 'full', 'blurb', 'Timing, fit & rules', NULL, 'Meeting points, duration, baggage limits, and adapter wattage caps — keep titles emotional, details here.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('84daf7f6-c4f4-4ba7-bfd8-3a8d98755887'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-pdp-context', 1, 'product_detail', 'pdp_below_context', 'full', 'blurb', 'Changes & refunds', NULL, 'Tour weather cancellations, transfer delays, and digital voucher reissues — keep policy links visible.', NULL, '/about', 'Our standards', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('6739517a-43bc-4d66-9589-7b9aeb1a41f2'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-recipe-title', 1, 'recipe', 'recipe_below_title', 'full', 'blurb', 'Self-catering shortcuts', NULL, 'Meal missions that suit apartments and hostels — cross-sell small appliances if you stock them.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('27604899-f87b-4386-b8b4-9d48c559178c'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-recipe-ingredients', 1, 'recipe', 'recipe_below_ingredients', 'full', 'blurb', 'Missing an ingredient?', NULL, 'Search or For You — Holmes bundles grocery add-ons with the cart.', NULL, '/for-you', 'Open For You', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('e7b7d3fa-faa4-441e-b68a-cf0ad6f388de'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-recipe-index', 1, 'recipe_index', 'recipes_index_below_header', 'full', 'blurb', 'Eat well on the road', NULL, 'Keep recipe cards mobile-first for airport and train contexts.', NULL, '/', 'Back to home', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('ae511855-7ac0-4087-8967-2f6a8848b3dd'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-checkout-summary', 1, 'checkout', 'checkout_above_summary', 'full', 'blurb', 'Tickets & fulfilment', NULL, 'Instant QR for tours, emailed vouchers for transfers, shipped goods for luggage — set expectations in one line.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('e589c8d0-d0e8-43ec-bf80-c0888985ec53'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-checkout-sidebar', 1, 'checkout', 'checkout_sidebar', 'full', 'blurb', 'Concierge & changes', NULL, 'Live chat for rescheduling tours or transfers — link to your SLA for same-day changes.', NULL, '/about', 'Contact', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('9b38cc17-c5af-4706-ab8f-f26ce80f3d2c'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-cart-above', 1, 'cart', 'cart_above_lines', 'full', 'blurb', 'Dates & overlap', NULL, 'Confirm tour times don’t clash with transfers; drop duplicate eSIMs or adapters.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('84d6a6d0-015b-45f9-9581-835a2de72d53'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-cart-below-bundle', 1, 'cart', 'cart_below_bundle', 'full', 'blurb', 'Add the missing leg', NULL, 'Maps, comfort, and data layers after tours and transfers are locked in.', NULL, '/catalogue?category=template-travel-accessories', 'Comfort & tech', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('25badd60-f1ab-4c99-8356-af67e9382f3a'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-offers', 1, 'offers', 'offers_below_header', 'full', 'blurb', 'Trip bundles', NULL, 'Stack tours + transfers + maps; keep copy short and let photography sell the emotion.', NULL, '/catalogue', 'Shop all', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('42a5e231-bdad-4177-8fd7-b601442880f8'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-promotions', 1, 'promotions', 'promotions_below_header', 'full', 'blurb', 'Seasonal departures', NULL, 'Half-term activities, summer boats, winter transfers — mirror what your CRM is emailing.', NULL, '/offers', 'See offers', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('e765d0c3-2585-4543-8501-2940465deaa3'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-travel-about', 1, 'about', 'about_main', 'full', 'image_blurb', 'Experiences first, retail that keeps up', NULL, 'Sell tours, transfers, and trip essentials with the same catalogue — CMS handles timing, imagery, and cross-sells.', 'https://images.pexels.com/photos/3223423/pexels-photo-3223423.png?auto=compress&cs=tinysrgb&h=650&w=940', '/catalogue', 'Browse shop', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
COMMIT;
